export default [
  {
    title: "Rock and Roll Highway",
    author: ["Sebastian Robertson"],
    illustrator: ["Adam Gustavson"],
    genre: "PB",
    subgenre: [],
    description:
      "Canadian guitarist and songwriter Robbie Robertson is known mainly for his central role in the musical group the Band. But how did he become one of Rolling Stone's top 100 guitarists of all time? Written by his son, Sebastian, this is the story of a rock-and-roll legend's journey through music, beginning when he was taught to play guitar at nine years old on a Native American reservation. Rock and Roll Highway is the story of a young person's passion, drive, and determination to follow his dream.",
  },
  {
    title: "A Poem For Peter",
    author: ["Andrea Davis Pinkney"],
    illustrator: ["Steve Johnson", "Lou Fancher"],
    genre: "PB",
    subgenre: [],
    description: "A celebration of the extraordinary life of Ezra Jack Keats, creator of The Snowy Day.",
  },
  {
    title: "Bee-bim Bop!",
    author: ["Linda Sue Park"],
    illustrator: ["Ho Baek Lee"],
    genre: "PB",
    subgenre: [],
    description: "Bee-bim bop (the name translates as “mix-mix rice”) is a traditional Korean dish of rice topped, and then mixed, with meat and vegetables. In bouncy rhyming text, a hungry child tells about helping her mother make bee-bim bop: shopping, preparing ingredients, setting the table, and finally sitting down with her family to enjoy a favorite meal. The energy and enthusiasm of the young narrator are conveyed in the whimsical illustrations, which bring details from the artist’s childhood in Korea to his depiction of a modern Korean American family. ",
  },
  {
    title: "I Can Make This Promise",
    author: ["Christine Day"],
    genre: "MG",
    subgenre: ["Domestic Fiction"],
    description: "All her life, Edie has known that her mom was adopted by a white couple. So, no matter how curious she might be about her Native American heritage, Edie is sure her family doesn’t have any answers. Until the day when she and her friends discover a box hidden in the attic—a box full of letters signed “Love, Edith,” and photos of a woman who looks just like her.Suddenly, Edie has a flurry of new questions about this woman who shares her name. Could she belong to the Native family that Edie never knew about? But if her mom and dad have kept this secret from her all her life, how can she trust them to tell her the truth now?",
  },
  {
    title: "Ghost Squad",
    author: ["Claribel Ortega"],
    genre: "MG",
    subgenre: ["Ghost Story","Fantasy Fiction"],
    description: "Shortly before Halloween, Lucely and her best friend, Syd, cast a spell that accidentally awakens malicious spirits, wreaking havoc throughout St. Augustine. Together, they must join forces with Syd's witch grandmother, Babette, and her tubby tabby, Chunk, to fight the haunting head-on and reverse the curse to save the town and Lucely's firefly spirits before it's too late.",
  },
  {
    title: "Tristan Strong Punches A Hole in the Sky",
    author: ["Kwame Mbalia"],
    genre: "MG",
    subgenre: ["Science Fiction", "Fantasy Fiction", "Adventure Fiction", "Paranormal Fiction"],
    description: "Seventh-grader Tristan Strong feels anything but strong ever since he failed to save his best friend when they were in a bus accident together. All he has left of Eddie is the journal his friend wrote stories in. Tristan is dreading the month he’s going to spend on his grandparents’ farm in Alabama, where he’s being sent to heal from the tragedy. But on his first night there, a sticky creature shows up in his bedroom and steals Eddie’s journal. Tristan chases after it — is that a doll? — and a tug-of-war ensues between them underneath a Bottle Tree. In a last attempt to wrestle the journal out of the creature’s hands, Tristan punches the tree, accidentally ripping open a chasm into the MidPass, a volatile place with a burning sea, haunted bone ships, and iron monsters that are hunting the inhabitants of this world. Tristan finds himself in the middle of a battle that has left black American gods John Henry and Brer Rabbit exhausted. In order to get back home, Tristan and these new allies will need to entice the god Anansi, the Weaver, to come out of hiding and seal the hole in the sky. But bartering with the trickster Anansi always comes at a price. Can Tristan save this world before he loses more of the things he loves?",
  },
  {
    title: "Super Fake Love Song",
    author: ["David Yoon"],
    genre: "YA",
    subgenre: ["Fiction", "Rom-com"],
    description: "When Sunny Dae—self-proclaimed total nerd—meets Cirrus Soh, he can’t believe how cool and confident she is. So when Cirrus mistakes Sunny’s older brother Gray’s bedroom—with its electric guitars and rock posters—for Sunny’s own, he sort of, kind of, accidentally winds up telling her he’s the front man of a rock band. Before he knows it, Sunny is knee-deep in the lie: He ropes his best friends into his scheme, begging them to form a fake band with him, and starts wearing Gray’s rock-and-roll castoffs. But no way can he trick this amazing girl into thinking he’s cool, right? Just when Sunny is about to come clean, Cirrus asks to see them play sometime. Gulp. Now there’s only one thing to do: Fake it till you make it. Sunny goes all in on the lie, and pretty soon, the strangest things start happening. People are noticing him in the hallways, and he’s going to football games and parties for the first time. He’s feeling more confident in every aspect of his life, and especially with Cirrus, who’s started to become not just his dream girl but also the real deal. Sunny is falling in love. He’s having fun. He’s even becoming a rocker, for real. But it’s only a matter of time before Sunny’s house of cards starts tumbling down. As his lies begin to catch up with him, Sunny Dae is forced to wonder whether it was all worth it—and if it’s possible to ever truly change.",
  },
  {
    title: "Everything Everything",
    author: ["Nicola Yoon"],
    genre: "YA",
    subgenre: ["Fiction"],
    description: "My disease is as rare as it is famous. Basically, I’m allergic to the world. I don’t leave my house, have not left my house in seventeen years. The only people I ever see are my mom and my nurse, Carla. But then one day, a moving truck arrives next door. I look out my window, and I see him. He's tall, lean and wearing all black—black T-shirt, black jeans, black sneakers, and a black knit cap that covers his hair completely. He catches me looking and stares at me. I stare right back. His name is Olly. Maybe we can’t predict the future, but we can predict some things. For example, I am certainly going to fall in love with Olly. It’s almost certainly going to be a disaster.",
  },
  {
    title: "Blazewrath Games",
    author: ["Amparo Ortiz"],
    genre: "YA",
    subgenre: ["Fantasy"],
    description: "Lana Torres has always preferred dragons to people. In a few weeks, sixteen countries will compete in the Blazewrath World Cup, a tournament where dragons and their riders fight for glory in a dangerous relay. Lana longs to represent her native Puerto Rico in their first ever World Cup appearance, and when Puerto Rico’s Runner—the only player without a dragon steed—is kicked off the team, she’s given the chance. But when she discovers that a former Blazewrath superstar has teamed up with the Sire—a legendary dragon who’s cursed into human form—the safety of the Cup is jeopardized. The pair are burning down dragon sanctuaries around the world and refuse to stop unless the Cup gets cancelled. All Lana wanted was to represent her country. Now, to do that, she’ll have to navigate an international conspiracy that’s deadlier than her beloved sport.",
  },
  {
    title: "Parable of the Sower",
    author: ["Octavia E. Butler"],
    genre: "A",
    subgenre: ["Science Fiction, Dystopian Fiction"],
    description: "When global climate change and economic crises lead to social chaos in the early 2020s, California becomes full of dangers, from pervasive water shortage to masses of vagabonds who will do anything to live to see another day. Fifteen-year-old Lauren Olamina lives inside a gated community with her preacher father, family, and neighbors, sheltered from the surrounding anarchy. In a society where any vulnerability is a risk, she suffers from hyperempathy, a debilitating sensitivity to others' emotions. Precocious and clear-eyed, Lauren must make her voice heard in order to protect her loved ones from the imminent disasters her small community stubbornly ignores. But what begins as a fight for survival soon leads to something much more: the birth of a new faith . . . and a startling vision of human destiny.",
  },
  {
    title: "After Life",
    author: ["Julia Alvarez"],
    genre: "A",
    subgenre: ["Domestic Fiction"],
    description: "Antonia Vega, the immigrant writer at the center of Afterlife, has had the rug pulled out from under her. She has just retired from the college where she taught English when her beloved husband, Sam, suddenly dies. And then more jolts: her bighearted but unstable sister disappears, and Antonia returns home one evening to find a pregnant, undocumented teenager on her doorstep. Antonia has always sought direction in the literature she loves—lines from her favorite authors play in her head like a soundtrack—but now she finds that the world demands more of her than words.",
  },
  {
    title: "Little Fires Everywhere",
    author: "Celeste Ng",
    genre: "A",
    subgenre: ["Domestic Fiction"],
    description: "In Shaker Heights, a placid, progressive suburb of Cleveland, everything is planned--from the layout of the winding roads, to the colors of the houses, to the successful lives its residents will go on to lead. And no one embodies this spirit more than Elena Richardson, whose guiding principle is playing by the rules. Enter Mia Warren--an enigmatic artist and single mother--who arrives in this idyllic bubble with her teenaged daughter Pearl, and rents a house from the Richardsons. Soon Mia and Pearl become more than tenants: all four Richardson children are drawn to the mother-daughter pair. But Mia carries with her a mysterious past and a disregard for the status quo that threatens to upend this carefully ordered community. When old family friends of the Richardsons attempt to adopt a Chinese-American baby, a custody battle erupts that dramatically divides the town--and puts Mia and Elena on opposing sides. Suspicious of Mia and her motives, Elena is determined to uncover the secrets in Mia's past. But her obsession will come at unexpected and devastating costs. Little Fires Everywhere explores the weight of secrets, the nature of art and identity, and the ferocious pull of motherhood--and the danger of believing that following the rules can avert disaster.",
  },
];
